[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-AAA_upscayl_4x_realesrgan-x4plus-anime
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-AAA_upscayl_4x_realesrgan-x4plus-anime
GtkTheme=oomox-AAA_upscayl_4x_realesrgan-x4plus-anime
IconTheme=oomox-AAA_upscayl_4x_realesrgan-x4plus-anime
MetacityTheme=oomox-AAA_upscayl_4x_realesrgan-x4plus-anime
