#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww_launch"
CFG="$HOME/.config/eww/"
EWW=`which eww`

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi

run_eww() {
    ${EWW} --config "$CFG" open-many \
    background \
    launchermenu \
    music
    }

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww
else
	${EWW} --config "$CFG" close \
					background launchermenu powermenu date music
	rm "$FILE"
fi
