#!/bin/bash

set -e

cd "$(dirname "$0")"
source ./common

platform="$(get_platform)"
if [ -z "$platform" ]; then 
  exit
fi

if [ -z "$1" ]; then
  "$platform"_get_source
else
  "$platform"_get_"$1"
fi