# Color override
set-option -sa terminal-overrides ",xterm*:Tc"

# Mouse support
set -g mouse on

# "Correct" Window numbering
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Detach on destroy
set -g detach-on-destroy off

# Plug-Ins
## Main Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'i
set -g @plugin 'tmux-plugins/tmux-yank'

## Custom Plugins
set -g @plugin 'christoomey/vim-tmux-navigator'
## set -g @plugin 'niksingh710/minimal-tmux-status'

# Keybinds
## Change Prefix
unbind C-b
set -g prefix C-q
bind C-q send-prefix

## Rebind / Remade classic binds
unbind '"'
unbind %
bind h split-window -h -c "#{pane_current_path}"
bind v split-window -v -c "#{pane_current_path}"

## Vim Tmux Navigator 
bind -n C-w source-file ~/.config/tmux/tmux_navigate_mode
bind C-w send-keys C-w # pass C-w to the program

## Yanking
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

## Status line
set -g status-bg 0
set -g status-interval 4    
set -g status-position top
set -g  status-right "#[bg=none,fg=brightred] #{?$PATH_OVERFLOW,$PANE_SHORTENED_PATH,$TMUX_PANE_HOME_SHORTENED_PATH} "
set -ga status-right "#[fg=brightyellow, bold]#(echo '#{pane_current_path}' | sed 's#$HOME#~#; s#\\([^/]*/[^/]*/\\).*\\(/[^/]*/.*\\)$#\\1 ... \\2#; s#/#  #g') #[fg=brightred,bold] #[none]%H:%M"
set -g status-right-length 150

set -g @online_icon  "#[fg=brightgreen,default] #[default]"
set -g @offline_icon "#[fg=red,default] #[default]"

set -g  status-left "#[fg=green,bold,bg=none]#{pane_mode}#[fg=green,none]"
set -ga status-left "#{?client_prefix,#[bg=none],#[fg=white]} #[fg=white,bold]#S#[fg=default] "
set -ga status-left "#[bg=none]#{?client_prefix,#[fg=red] ,#[fg=default]  }"
set -g status-left-length 80

# Windows status {{{
setw -g window-status-activity-style fg=brightyellow 
setw -g window-status-bell-style     fg=red
setw -g window-status-format         "#[fg=brightyellow]#I#[fg=brightgreen]#F #[fg=brightwhite]#W"
setw -g window-status-current-format "#[fg=yellow]#I#[fg=green]#F #[fg=white,bold,underscore]#W"
setw -g window-status-separator      "#[fg=brightwhite,bold]  "
set -g status-justify left


###########
# CAUTION #
###########

# Bootstrap TMP
if "test ! -d ~/.local/share/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.local/share/tmux/plugins/tpm && ~/.local/share/tmux/plugins/tpm/bin/install_plugins'"

# Initialize TMP
run '${XDG_DATA_HOME:-${HOME}/.local/share}/tmux/plugins/tpm/tpm'


